<?php
$items = $this->getValuesCollection()->retrieveAll()->getItems();
//Mage::getModel('dc_catalog/AttributeInfo')->load($this->getAttributePageId());
if (!count($items) > 0) {
    return '';
}

?>
<div class="attribute-slider-items">
    <?php
    $thumbnail_width = 113;
    $thumbnail_height = 113;
    foreach ($items as $item) {
        if (($file = Mage::getBaseDir('media') . DS . 'catalog' . DS . 'attribute' . DS . $item->getImage()) && is_file($file)) {

            $baseDir = Mage::getSingleton('catalog/product_media_config')->getBaseMediaPath();

            $imgUrl = Mage::helper('dc_catalog/image')
                ->initImage($this->getAttributeCode(), $item->getImage())
                ->resize($thumbnail_width, $thumbnail_height)
                ->__toString();
            $imgHtml = '<img
			width="' . ($thumbnail_width ? $thumbnail_width : $width) . '"
	        src="' . $imgUrl . '"
	        alt="' . $this->htmlEscape($item->getValue()) . '"
	        title="' . $this->htmlEscape($item->getValue()) . '"
	        />';
            if ($imgHtml) {
                echo '<a style="display:block;float:left;height:100%;min-height:1px;margin:10px" href="' . $this->getUrl('/') . $item->getAttributeCode() . '/' . $item->getIdentifier() . '" title="' . $item->getName() . '">' . $imgHtml . '</a>';
            }
        } else {
            echo '<a style="display:block;float:left;height:100%;min-height:1px;margin:10px" href="' . $this->getUrl('/') . $item->getAttributeCode() . '/' . $item->getIdentifier() . '" title="' . $item->getName() . '">' . $item->getValue() . '</a>';
        }
    }

    ?>
</div>